name: "Frontend admin tests"

on: [push]

jobs:
  withplugins:
    name: with plugins
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run sauce-connect-action
      shell: bash
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        TRAVIS_JOB_NUMBER: ${{ github.run_id }}-${{ github.run_number }}-${{ github.job }}
      run: tests/frontend/travis/sauce_tunnel.sh

    - name: Install all dependencies and symlink for ep_etherpad-lite
      run: bin/installDeps.sh

      # We intentionally install a slightly older ep_align version to test update against
    - name: Install etherpad plugins
      run: npm install ep_align@0.3.18

    - name: export GIT_HASH to env
      id: environment
      run: echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.sha }})"

    - name: Write custom settings.json with loglevel WARN
      run: "sed 's/\"loglevel\": \"INFO\",/\"loglevel\": \"WARN\",/' < settings.json.template > settings.json"

    - name: Write custom settings.json that enables the Admin UI tests
      run: "sed -i 's/\"enableAdminUITests\": false/\"enableAdminUITests\": true,\\n\"users\":{\"admin\":{\"password\":\"changeme\",\"is_admin\":true}}/' settings.json"

    - name: Remove standard frontend test files, so only admin tests are run
      run: mv tests/frontend/specs/admin /tmp && mv /tmp/admin* tests/frontend/specs

    - name: Run the frontend admin tests
      shell: bash
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        TRAVIS_JOB_NUMBER: ${{ github.run_id }}-${{ github.run_number }}-${{ github.job }}
        GIT_HASH: ${{ steps.environment.outputs.sha_short }}
      run: |
        tests/frontend/travis/runner.sh
